// Imagine you're getting a special label maker (Metadata) from a toolbox called "next".
// This is like telling the website, "I need a way to add information labels to my website."
import type { Metadata } from "next";

// This is like getting two specific fonts (Geist and Geist_Mono) from Google's font collection.
// Think of it as ordering two specific styles of handwriting from Google's handwriting store.
import { Geist, Geist_Mono } from "next/font/google";

// This is like bringing in a style guide that applies to the entire website.
// Imagine importing a rulebook that says, "All pages should follow these design rules."
import "./globals.css";

// This creates a variable called geistSans that holds our main font.
// It's like setting up a special pen with the Geist handwriting style that anyone can use.
const geistSans = Geist({
  // This gives the font a nickname (--font-geist-sans) that CSS can use.
  // Think of it as putting a label on the pen so others know which one to grab.
  variable: "--font-geist-sans",
  // This specifies we only need the Latin alphabet characters.
  // Imagine saying, "I only need the English letters, not Chinese or Arabic characters."
  subsets: ["latin"],
});

// This creates another variable for our monospace font (the one where each letter takes up the same width).
// It's like setting up a special typewriter with evenly-spaced letters.
const geistMono = Geist_Mono({
  // This gives the monospace font its own nickname for CSS to use.
  // Like putting a different label on the typewriter.
  variable: "--font-geist-mono",
  // Again, we only need Latin alphabet characters.
  // "I only need English letters for this typewriter too."
  subsets: ["latin"],
});

// This creates information that search engines and browsers can read about your website.
// It's like creating the cover page for a book, with the title and a brief description.
export const metadata: Metadata = {
  // This sets the title that appears in the browser tab.
  // Think of it as the title printed on the spine of a book.
  title: "Create Next App",
  // This is a short description of what the website is about.
  // Like the blurb on the back cover of a book that summarizes what it's about.
  description: "Generated by create next app",
};

// This creates the main blueprint for how every page in your website should be structured.
// Think of it as designing the basic frame of a house that all rooms must fit within.
export default function RootLayout({
  // "children" represents whatever page content needs to go inside this layout.
  // Imagine this as a placeholder saying, "The specific room details will be added here later."
  children,
}: Readonly<{
  // This line defines what type of content "children" can be (React components).
  // It's like specifying, "This space can hold any standard room design that follows our building code."
  children: React.ReactNode;
}>) {
  // This returns the actual HTML structure that will wrap around every page.
  // Think of this as saying, "Here's how we'll build the frame of the house."
  return (
    // This creates the outermost HTML element and sets the language to English.
    // Like saying, "The house will have these outer walls, and the people inside speak English."
    <html lang="en">
      {/* This creates the body element where all visible content goes.
          Think of this as the interior space of the house where people actually live. */}
      <body
        // This applies our fonts and makes text smoother.
        // It's like saying, "Paint the interior walls with these specific paints, and make sure the finish is smooth."
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* This is where the actual page content (children) gets inserted.
            Imagine this as saying, "And here's where the furniture and decorations for each specific room will go." */}
        {children}
      </body>
    </html>
  );
}
